name: ml_test

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip:
    - astroid==2.15.5
    - black==23.3.0
    - cfgv==3.3.1
    - click==8.1.3
    - contourpy==1.1.0
    - coverage==7.2.7
    - cycler==0.11.0
    - dill==0.3.6
    - distlib==0.3.6
    - filelock==3.12.2
    - flake8==6.0.0
    - fonttools==4.40.0
    - identify==2.5.24
    - imbalanced-learn==0.10.1
    - imblearn==0.0
    - iniconfig==2.0.0
    - isort==5.12.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - lazy-object-proxy==1.9.0
    - matplotlib==3.7.1
    - mccabe==0.7.0
    - mypy==1.4.0
    - mypy-extensions==1.0.0
    - nodeenv==1.8.0
    - numpy==1.25.0
    - packaging==23.1
    - pandas==2.0.2
    - pathspec==0.11.1
    - Pillow==9.5.0
    - platformdirs==3.8.0
    - pluggy==1.2.0
    - pre-commit==3.3.3
    - pyarrow==12.0.1
    - pycodestyle==2.10.0
    - pyflakes==3.0.1
    - pylint==2.17.4
    - pyparsing==3.1.0
    - pytest==7.4.0
    - pytest-cov==4.1.0
    - python-dateutil==2.8.2
    - pytz==2023.3
    - PyYAML==6.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.12.2
    - six==1.16.0
    - threadpoolctl==3.1.0
    - tomlkit==0.11.8
    - typing_extensions==4.6.3
    - tzdata==2023.3
    - virtualenv==20.24.0
    - wrapt==1.15.0
